apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone-app
  labels:
    app: devops-capstone-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-capstone-app
  template:
    metadata:
      labels:
        app: devops-capstone-app
    spec:
      containers:
      - name: devops-capstone-app
        image: ghcr.io/praveenjayaprakash-jp/devops-capstone-project:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: PORT
          value: "8000"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: devops-capstone-service
  labels:
    app: devops-capstone-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: devops-capstone-app
